Enhance CI/CD workflows: update deploy and test configurations to use actions/checkout and actions/setup-python, specify Python version 3.12, and include steps for dependency installation and deployment to GitHub Pages.

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,7 +1,46 @@
 name: CI
-on:  [workflow_dispatch, pull_request, push]
+
+on: [workflow_dispatch, pull_request, push]
 
 jobs:
   test:
     runs-on: ubuntu-latest
-    steps: [uses: answerdotai/workflows/nbdev-ci@master]
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: "3.12"
+
+      - name: Test with nbdev
+        env:
+          OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
+        run: |
+          set -ux
+          python -m pip install --upgrade pip
+          pip install -U "nbdev>=2,<3"
+          echo "Doing editable install..."
+          test -f setup.py && pip install -e ".[dev]"
+          echo "Check we are starting with clean git checkout"
+          if [[ `git status --porcelain -uno` ]]; then
+            git diff
+            echo "git status is not clean"
+            false
+          fi
+          echo "Trying to strip out notebooks"
+          nbdev_clean
+          echo "Check that strip out was unnecessary"
+          git status -s
+          if [[ `git status --porcelain -uno` ]]; then
+            git status -uno
+            echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
+            false
+          fi
+          nbdev_export
+          if [[ `git status --porcelain -uno` ]]; then
+            echo "::error::Notebooks and library are not in sync. Please run nbdev_export."
+            git status -uno
+            git diff
+            exit 1
+          fi
+          nbdev_test --flags "notest"
